apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafna
  labels:
    app: grafana
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: grafana
